### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by wong-way** [FRED5DON/ui-picture-bd-marker#1]
目前图像标注的开源插件较少，目前基于jq的有一个imagelabel，能在vue框架下使用的更少，能否能提供一个完整的使用demo

**Comment by sunshengfei** [comment]
我封装的vue的你看看 npm上有 https://www.npmjs.com/package/vue-picture-bd-marker
demo目前没有，都是真实的项目了，有时间会搞一个 你先看看上面那个
