### ISSUE TITLE
当图片宽高比例很大的话我标注时标注不上数据，无效果

### ISSUE THREAD

**Issue by qunqunyang** [FRED5DON/ui-picture-bd-marker#10]
当我的图片是700*11000时这时候我在页面是加了滚动条，当我标注一小部分内容时此时标注不上，必须大面积标注 才能标注上内容， 比如宽160高30 这时标注不上，无标注数据返回。这种情况有没有解决办法呢。

**Comment by sunshengfei** [comment]
最新版本已修复，可以通过设置width="auto" 或者ratio=0
