### ISSUE TITLE
标注框不可旋转

### ISSUE THREAD

**Issue by xiyuan27** [FRED5DON/ui-picture-bd-marker#13]
对于某些扭曲的图片，标注框最好可以旋转。
1. 旋转图片不行，因为某些标注框要向转旋2度，另外一个标注框需要向右旋3度

**Comment by sunshengfei** [comment]
本仓库只维护，不再扩展，代码开源可自行修改
如有需要，请查看对应的svg版（支持画圆 https://www.npmjs.com/package/ui-picture-svg-marker）

2021年1月19日 19:12，xiyuan27 <notifications@github.com<mailto:notifications@github.com>> 写道：



对于某些扭曲的图片，标注框最好可以旋转。

  1.  旋转图片不行，因为某些标注框要向转旋2度，另外一个标注框需要向右旋3度
