### ISSUE TITLE
框的tag样式可以调吗 另外有没有方法可以实现点某个地方实现选择框高亮的功能

### ISSUE THREAD

**Issue by tanbenw** [FRED5DON/ui-picture-bd-marker#18]
![企业微信截图_f8a37ae1-eb9c-4da0-a32a-986301a03c94](https://user-images.githubusercontent.com/37618640/119598480-9a76ce00-be15-11eb-831e-d99c65435a14.png)

**Comment by sunshengfei** [comment]
1、实现点某个地方实现选择框高亮的功能 marker.selectMarkerByTagId 
2、tag样式可以自己写css选择器进行覆盖

**Comment by tanbenw** [comment]
第一点是需要自己写方法实现吗 有没有api

**Comment by sunshengfei** [comment]
@13160671810  就是api呀，获取到marker对象直接selectMarkerByTagId

**Comment by tanbenw** [comment]
> @13160671810 就是api呀，获取到marker对象直接selectMarkerByTagId
![截屏2021-05-26 下午2 47 01](https://user-images.githubusercontent.com/37618640/119614847-598cb280-be31-11eb-974c-dadd970c04d2.png)
![截屏2021-05-26 下午2 47 41](https://user-images.githubusercontent.com/37618640/119614859-5db8d000-be31-11eb-8a28-4cdc3cad6c80.png)
显示没有这个方法

**Comment by sunshengfei** [comment]
emm,你用的是vue-marker吧，issue提错地方了。。
Vue 这个封装的有点问题 getMarker() 需要调用两次，先临时这样解决吧，这几天我抽时间解决下
marker.getMarker().getMarker().selectMarkerByTagId

**Comment by tanbenw** [comment]
![截屏2021-05-26 下午3 10 12](https://user-images.githubusercontent.com/37618640/119617515-84c4d100-be34-11eb-92ee-f41fa8834350.png)
![截屏2021-05-26 下午3 09 19](https://user-images.githubusercontent.com/37618640/119617537-87bfc180-be34-11eb-9692-272fccb2a64b.png)
🆘~~ 来自一名Java开发的绝望

**Comment by sunshengfei** [comment]
![image](https://user-images.githubusercontent.com/8654525/119618025-00bf1900-be35-11eb-8c67-e50db7b8bbd1.png)

![image](https://user-images.githubusercontent.com/8654525/119618179-2ba96d00-be35-11eb-8d7b-3a4891dbe5e7.png)

哥来拯救你，加个vx吧 ： fabyuxuan
