### ISSUE TITLE
使用vue控件回调数据有误

### ISSUE THREAD

**Issue by mrlinjun** [FRED5DON/ui-picture-bd-marker#2]
https://vmarker.sagocloud.com/about/#a-about-about
我在使用vue控制时，在移动标注和删除标注时，回调函数返回的data是有误的，一直保持不变。

**Comment by sunshengfei** [comment]
你好，感谢反馈，能否提供相关截图，信息如下：

1. 使用的是ui-picture-bd-marker还是vue-picture-bd-marker。
2. 你所使用的浏览器内核（ms、webkit、Mozilla、opera）
3. 在移动标注和删除标注时，回调函数以及返回的data数据截图。
4. 如果允许的话可以提供操作录屏。


===============================
Fred Don
https://sagocloud.com/
===============================

2019年10月10日 15:57，mrlinjun <notifications@github.com<mailto:notifications@github.com>> 写道：


https://vmarker.sagocloud.com/about/#a-about-about
我在使用vue控制时，在移动标注和删除标注时，回调函数返回的data是有误的，一直保持不变。

**Comment by mrlinjun** [comment]
使用的是 ：vue-picture-bd-marker
浏览器版本：谷歌浏览器 版本 76.0.3809.132（正式版本） （64 位）
操作步骤：
1、新增三个标注，获取到的标注信息为
[{"tag":"temp@C71B809622766729","tagName":"请选择或添加新标签","position":{"x":"11.389%","y":"10.579%","x1":"23.296%","y1":"27.828%"},"uuid":"C71B809622766729"},{"tag":"temp@4312C3F013522FC8","tagName":"请选择或添加新标签","position":{"x":"37.274%","y":"16.329%","x1":"47.757000000000005%","y1":"40.937%"},"uuid":"4312C3F013522FC8"},{"tag":"temp@9B05ECFDF112FF48","tagName":"请选择或添加新标签","position":{"x":"70.924%","y":"37.487%","x1":"80.501%","y1":"58.646%"},"uuid":"9B05ECFDF112FF48"}]
2、删除一个标注，获取到的标注信息为
[{"tag":"temp@C71B809622766729","tagName":"请选择或添加新标签","position":{"x":"11.389%","y":"10.579%","x1":"23.296%","y1":"27.828%"},"uuid":"C71B809622766729"},{"tag":"temp@4312C3F013522FC8","tagName":"请选择或添加新标签","position":{"x":"37.274%","y":"16.329%","x1":"47.757000000000005%","y1":"40.937%"},"uuid":"4312C3F013522FC8"}] -- 目前的表现是正常的
3、再删除一个标注，理论上获取到的信息应该只剩余一个标注，但是结果还是有两个
[{"tag":"temp@C71B809622766729","tagName":"请选择或添加新标签","position":{"x":"11.389%","y":"10.579%","x1":"23.296%","y1":"27.828%"},"uuid":"C71B809622766729"},{"tag":"temp@4312C3F013522FC8","tagName":"请选择或添加新标签","position":{"x":"37.274%","y":"16.329%","x1":"47.757000000000005%","y1":"40.937%"},"uuid":"4312C3F013522FC8"}]
请帮忙看一下是什么情况

**Comment by sunshengfei** [comment]
+Q 419102565


2019年10月10日 16:23，mrlinjun <notifications@github.com<mailto:notifications@github.com>> 写道：


使用的是 ：vue-picture-bd-marker
浏览器版本：版本 76.0.3809.132（正式版本） （64 位）
操作步骤：
1、新增三个标注，获取到的标注信息为
[{"tag":"temp@C71B809622766729","tagName":"请选择或添加新标签","position":{"x":"11.389%","y":"10.579%","x1":"23.296%","y1":"27.828%"},"uuid":"C71B809622766729"},{"tag":"temp@4312C3F013522FC8","tagName":"请选择或添加新标签","position":{"x":"37.274%","y":"16.329%","x1":"47.757000000000005%","y1":"40.937%"},"uuid":"4312C3F013522FC8"},{"tag":"temp@9B05ECFDF112FF48","tagName":"请选择或添加新标签","position":{"x":"70.924%","y":"37.487%","x1":"80.501%","y1":"58.646%"},"uuid":"9B05ECFDF112FF48"}]
2、删除一个标注，获取到的标注信息为
[{"tag":"temp@C71B809622766729","tagName":"请选择或添加新标签","position":{"x":"11.389%","y":"10.579%","x1":"23.296%","y1":"27.828%"},"uuid":"C71B809622766729"},{"tag":"temp@4312C3F013522FC8","tagName":"请选择或添加新标签","position":{"x":"37.274%","y":"16.329%","x1":"47.757000000000005%","y1":"40.937%"},"uuid":"4312C3F013522FC8"}] -- 目前的表现是正常的
3、再删除一个标注，理论上获取到的信息应该只剩余一个标注，但是结果还是有两个
[{"tag":"temp@C71B809622766729","tagName":"请选择或添加新标签","position":{"x":"11.389%","y":"10.579%","x1":"23.296%","y1":"27.828%"},"uuid":"C71B809622766729"},{"tag":"temp@4312C3F013522FC8","tagName":"请选择或添加新标签","position":{"x":"37.274%","y":"16.329%","x1":"47.757000000000005%","y1":"40.937%"},"uuid":"4312C3F013522FC8"}]
请帮忙看一下是什么情况

**Comment by sunshengfei** [comment]
已更新，请使用最新版
===============================
