### ISSUE TITLE
使用vue-picture-bd-marker的图片展示严重比例失调问题

### ISSUE THREAD

**Issue by huicrh** [FRED5DON/ui-picture-bd-marker#3]
展示的图片heigh一直为781.313px，宽度为100%。造成图片的缩放比例与原图片不符合，图片变形。

**Comment by sunshengfei** [comment]
宽度目前还不支持百分比，必须是px

**Comment by huicrh** [comment]
比如我图片原始宽高是540*540，采用插件设置了imgUrl到界面是1222*781。比例和原图片差别太大。能否设置展示图片的宽高为1：1呢，ratio属性不能达到这种效果

**Comment by huicrh** [comment]
比如我图片原始宽高是540乘以540，采用插件设置了imgUrl到界面是1222乘以781

**Comment by sunshengfei** [comment]
ok，我记录下，今天抽空解决下

**Comment by sunshengfei** [comment]
你好，此问题预计下个版本会优化，但目前手上几个事情还比较紧急，所以给你提供临时解决方案，如下：
```
<ui-marker  ref="aiPanel-editor" :ratio="ratio"  @vmarker:onImageLoad="onImageLoad" >
</ui-marker>
``
在onImageLoad方法中再次更改ratio的值即可。

**Comment by huicrh** [comment]
你好，感谢给出解决方案。已解决该问题。
1.ratio必须配合width才能生效，而且ratio值是"16/9"也不对，必须是一个Number类型，不能是字符串。这样看来技术文档好像有点问题。
2.用了该解决方案确实能解决图片缩放的问题，但是对于移动标注矩形框还会有问题。具体表现为横向拖动和纵向拖动相同距离，框的移动距离是不同的。

**Comment by sunshengfei** [comment]
如果你用:ratio=‘16/9’ 这是可以的 注意前面的冒号

发自我的iPhone

在 2019年10月25日，16:02，huicrh <notifications@github.com> 写道：

﻿

你好，感谢给出解决方案。已解决该问题。
1.ratio必须配合width才能生效，而且ratio值是"16/9"也不对，必须是一个Number类型，不能是字符串。这样看来技术文档好像有点问题。
2.用了该解决方案确实能解决图片缩放的问题，但是对于移动标注矩形框还会有问题。具体表现为横向拖动和纵向拖动相同距离，框的移动距离是不同的。
