### ISSUE TITLE
修改标注的大小和名称的问题

### ISSUE THREAD

**Issue by huicrh** [FRED5DON/ui-picture-bd-marker#4]
修改了标注的位置，和名称，发现对应的onUpdated(data)函数的data值还是未更改之前的值。
1.采用 this.$refs['aiPanel-editor'].getMarker().setTag({
            tagName: this.selectValue
          })无法设置当前标注对应的名称。界面的名称改变了，但是data值tagname未改变
2.更改标注的大小位置，data值中position未改变

**Comment by sunshengfei** [comment]
你好，我并未发现坐标未更新此问题，目前已在[vue-ui-picture-bd-marker](https://github.com/FRED5DON/vue-ui-picture-bd-marker)创建了**test**分支,
你可以自己clone下来npm run dev排查下，如果遇到请提供重现步骤，谢谢

**Comment by huicrh** [comment]
你好目前我对于vue不是很熟悉，所以暂时不知道如何排查 
目前我是这样使用1.@vmarker:onUpdated="onUpdated"
    2.onUpdated(data) {
        this.$emit('vmarker:onUpdated', data, this.uniqueKey)
      }
这个data的值就算界面的标注大小改变，data值也不变是什么原因

**Comment by sunshengfei** [comment]
你可以克隆提到的那个分支本地跑一下看看 我明天再调试下 改下源码

发自我的iPhone

在 2019年10月25日，16:11，huicrh <notifications@github.com> 写道：

﻿

你好目前我对于vue不是很熟悉，所以暂时不知道如何排查
目前我是这样使用1.@vmarker<https://github.com/vmarker>:onUpdated="onUpdated"
2.onUpdated(data) {
this.$emit('vmarker:onUpdated', data, this.uniqueKey)
}
这个data的值就算界面的标注大小改变，data值也不变是什么原因

**Comment by sunshengfei** [comment]
你如果是基于`ui-picture-bd-marker`自己封装的请注意保持html结构，我有说明的，最好参照`vue-picture-bd-marker`。
你使用Vue的话，建议使用我封装的vue插件[vue-picture-bd-marker](https://www.npmjs.com/package/vue-picture-bd-marker)
